### ISSUE TITLE
maven 仓库

### ISSUE THREAD

**Issue by lakakala** [HMS-Core/hms-push-serverdemo-java#1]
这个能统一上传到maven官方仓库吗 方便集成 也方便版本管理

**Comment by Mike-mei** [comment]
你好，目前没有上传maven官方仓库的计划。
Push 服务端Java示例代码下载渠道除[Github](https://github.com/HMS-Core/hms-push-serverdemo-java)还有[联盟官网](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples/server-java-sample-code-0000001051066002)

**Comment by lakakala** [comment]
那可以每次修改有一个tag 或者release 这样我们方便更新版本
