### ISSUE TITLE
BadgeNotification构造器初始化问题

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#10]
**Description**
BadgeNotification类中，原始代码：
    public BadgeNotification(Integer addNum, String badgeClass) {
        this.addNum = builder().addNum;   <----这一行
        this.badgeClass = badgeClass;
    }

**Expected behavior**
应该改为：
    public BadgeNotification(Integer addNum, String badgeClass) {
        this.addNum = addNum;
        this.badgeClass = badgeClass;
    }

**Comment by Mike-mei** [comment]
你好，提出的几个issue，Push服务端开发团队正在确认，有进展会及时回复

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
