### ISSUE TITLE
WebNotification类中的vibrate应该用List<Integer>

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#11]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References-V5/https-send-api-0000001050986197-V5#ZH-CN_TOPIC_0000001134031085__p9325108132317
vibrate[]类型为integer，因此建议WebNotification类中的vibrate使用List<Integer>而不是List<Object>，同时Builder中相应位置需做改动。

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
