### ISSUE TITLE
AndroidConfig缺少receiptId

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#13]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/https-send-api-0000001050986197#ZH-CN_TOPIC_0000001134031085__p443363181111
AndroidConfig有receipt_id，而demo中的AndroidConfig类并没有。

建议在AndroidConfig类中增加：
```
    @JSONField(name = "receipt_id")
    private String receiptId;
```
同时修改Builder、AndroidConfig.AndroidConfig(Builder)中相关代码

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
