### ISSUE TITLE
ApnsHmsOptions类中目标用户类型枚举值错误

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#14]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/https-send-api-0000001050986197#ZH-CN_TOPIC_0000001134031085__p188911438143814
目标用户类型，取值如下：
1：测试用户
2：正式用户
3：VoIP用户

但是ApnsHmsOptions类中：
```
    private static final int TEST_USER = 1;
    private static final int FORMAL_USER = 1;
    private static final int VOIP_USER = 1;
```
期望改为
```
    private static final int TEST_USER = 1;
    private static final int FORMAL_USER = 2;
    private static final int VOIP_USER = 3;
```

考虑到没有枚举类TargetUserType，因此建议上面的三个枚举值从private改为public。

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
