### ISSUE TITLE
AndroidNotification缺少profileId

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#15]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/https-send-api-0000001050986197#ZH-CN_TOPIC_0000001134031085__p1167774704012
AndroidNotification有profile_id，而demo中的AndroidNotification类并没有。

建议在AndroidNotification类中增加：
```
    @JSONField(name = "profile_id")
    private String profileId;
```
同时修改Builder、AndroidNotification.AndroidNotification(Builder)中相关代码

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
