### ISSUE TITLE
ResponceCodeProcesser中缺少部分错误码

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#16]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/https-send-api-0000001050986197#ZH-CN_TOPIC_0000001134031085__p173287813234
存在如下错误码：

- 80100017：同时发送的Topic任务超过100个。
- 80100018：消息体内容验签不通过。
- 80300011：无权限发送高级别通知消息。
- 80600003：请求Oauth服务失败。

但是ResponceCodeProcesser类中并不存在这些错误码，建议增加：

```
    // 错误码80100016后增加
    put(80100017, "Send task cannot be more than 100 concurrently");
    put(80100018, "The message body cannot pass the verification");
    // 错误码80300010后增加
    put(80300011, "No permission to send high-level notification messages");
    put(80600003, "Request OAuth service failed");
```

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
