### ISSUE TITLE
AndroidNotification.check(Notification)中提示信息需要更新

### ISSUE THREAD

**Issue by superinkfish** [HMS-Core/hms-push-serverdemo-java#18]
根据文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/https-send-api-0000001050986197#ZH-CN_TOPIC_0000001134031085__p1732019820230，style的取值为0、1、3。
AndroidNotification.check(Notification)中有一段提示信息“style should be one of 0:default, 1: big text, 2: big picture”，这里推测2.big picture应该是已经下线或隐藏，那么提示信息建议改为："style should be one of 0:default, 1: big text, 1: inbox"

**Comment by Mike-mei** [comment]
这个问题新版本中已经解决，参考 5635d3e
